@startuml trafico de trenes

class Tren {

}

class TramoVia {

}

class Sensor {

}

class SensorTren {

}

class SensorVia {

}

class Semaforo {

}

class Alerta {

}

class SistemaControl {

}

' Herencia
Sensor <|-- SensorTren
Sensor <|-- SensorVia

' Relaciones del sistema
SistemaControl "1" o-- "1..*" Tren : gestiona 
SistemaControl "1" o-- "1..*" TramoVia : monitorea 

' Relaciones entre entidades físicas
TramoVia "1" -- "1..*" Semaforo : contiene 
TramoVia "1" -- "1..*" SensorVia : equipa 
Tren "1" -- "1..*" SensorTren : equipa

' Generación de alertas
Sensor -- "0..*" Alerta : genera

@enduml